title: Build a robot buggy
hero_image: images/banner.png
description: Build and control a robot buggy
original_url: 
theme: cc-prototype
duration: 3
listed: false
ingredient: false
interests: "physical computing, robots"
technologies: "electronics, physical computing, python"
steps:
  - title: Introduction
  - title: What you will need
  - title: Setup
  - title: Assemble you robot
  - title: Program your robot
