title: Build a robot buggy
hero_image: images/banner.png
description: Build and control a robot buggy
original_url: 
theme: violet
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: design-0, programming-2, phys-comp-2, manufacture-1, community-0
interests: "physical computing, robots, big-project"
technologies: "electronics, physical computing, python"
steps:
  - title: Introduction
  - title: What you will need
  - title: Set up your motors
  - title: Left, right, forward, backward
  - title: Assemble your robot
  - title: "Challenge: program your robot"
